version: '3.8'

services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=catto
    ports:
      - '3310:3306'
    volumes:
      - database_data:/var/lib/mysql

  redis:
    image: redis
    ports:
      - '6379:6379'

  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    ports:
      - '3000:3000'

volumes:
  database_data:
